repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        exclude: ^cloudformation/.*
      - id: end-of-file-fixer
        exclude: ^cloudformation/.*
      - id: check-yaml
        exclude: ^cloudformation/.*
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.30.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint]
        exclude: ^cloudformation/.*
