######## Cassandra Backup Schedules ########
backups:
  - name: Schedule a backup to Google Cloud
    remote_type: googlecloudstorage
    cluster: lab
    datacenters: dc1
    remote_path: axonops-training/lab/dc1
    local_retention: 10d
    remote_retention: 60d
    tag: "scheduled backup"
    timeout: 10h
    remote: true
    schedule: true
    schedule_expr: 0 1 * * *
    region: eu
    service_account_credentials: private
